apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainserver
  namespace: devproject
spec:
  replicas: 2
  selector:
    matchLabels:
      apptype: web
      env: dev
  template:
    metadata:
      name: maintemplate
      labels:
        apptype: web
        env: dev
    spec:
      containers:
        - image: nishal03/javaimage:latest
          imagePullPolicy: IfNotPresent
          name: videocon
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # restartPolicy: Always
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: mainsvc
  namespace: devproject
spec:
  type: LoadBalancer
  ports:
    - name: tomcat
      port: 80 # service port
      protocol: TCP
      targetPort: 8080 # container port exposed as per in image
  selector:
    apptype: web
    env: dev
